### PR TITLE
More Graphics and minor tweaks

### PR DESCRIPTION
**Pull request by CatmanIX**
Everything should be more minecrafty now. 

I may go into the QT stuff and make the client look similar to the minecraft launcher later...

Also, no offense but the coin logo looks like crap. I haven't changed it but would you consider using something like [this](http://goo.gl/PhFhR) instead?

### CODE REVIEW

**Comment by craftcoin** [comment]
Take a peek at the more current logo, thats the direction i think i'd like to go. Yes, the older one was horrible! I made it one day before work. But the newer one is a bit better.

**Comment by craftcoin** [comment]
It looks like our efforts have overlapped a little here, but honestly most of the changes are identical (hashrate calculation) or close enough (copyright info) 

The graphics are also all great.

**Comment by CatmanIX** [comment]
Most of the overlap was do to a bad merge making me recommit things.

And I'm talking about the newest logo, the one with the diamond plastered on it. It looks absolutely dreadful. The old one was better than this (aside from the bit of white artifacts around it).

If it's just a rough draft that's fine I guess, I can see about making it look a little nicer, but as it is people will take one glance at it and completely ignore the coin.

**Comment by craftcoin** [comment]
If you would like to make one up, I'm all for it. The vision is to have it look "minecrafty" but not incorporate enough to get copyright infringement issues. If you want to make something that fits this idea, but looks more appealing I certainly welcome it. In fact you have been a great deal of help throughout this entire project, so any contributions are appreciated. 

--------- Original Message --------- Subject: Re: [craftcoin] More Graphics and minor tweaks (#5)

**Comment by CatmanIX** [comment]
Well, this is what I'm working on atm, what do you think?

http://goo.gl/6xduJ

I'm planning on swapping the emerald for a ruby in the testnet version (since rubies are kinda like minecrafts testing emeralds).

**Comment by craftcoin** [comment]
yes actually. i do like it

--------- Original Message --------- Subject: Re: [craftcoin] More Graphics and minor tweaks (#5)

**Comment by CatmanIX** [comment]
awesome, any suggestions for improvements or should I roll this out and make icons?

**Comment by craftcoin** [comment]
i say roll it out

--------- Original Message --------- Subject: Re: [craftcoin] More Graphics and minor tweaks (#5)

**Pull request merged**
