### PR TITLE
Removed junk and added .gitignore

### PR DESCRIPTION
**Pull request by CatmanIX**
Binaries and temporary files shouldn't be committed if possible, .gitignore should prevent this.

### CODE REVIEW

**Comment by CatmanIX** [comment]
No prob, do you know how to merge this into your master?

**Comment by craftcoin** [comment]
No, I do not. (sorry, im not ignoring you, just working to get this all going.) I finally have coins mining on the network. I will look at the changes now. 

I wondered if you would consider being paid in bitcoin/litecoin to modify this plugin http://dev.bukkit.org/bukkit-mods/satoshis/ to work with craftcoin. 

I dont usually ask this type of stuff from strangers, but its worth a shot. If so, estimate how much, and if not... thats cool too :)

Thanks 

--------- Original Message --------- Subject: Re: [craftcoin] Removed junk and added .gitignore (#1)

**Comment by CatmanIX** [comment]
Ah, well the easiest way to merge this in is to use the big green "Merge Pull Request" button that should be just above the comment box here. http://goo.gl/miD5Q

If not, use the command line to go into your local craftcoin repository and use "git pull https://github.com/CatmanIX/craftcoin.git" to pull my changes into your local repo and then push back to github.

As for the satoshis plugin, I'll take a look at it but I make no promises, I haven't really poked around with bukkit plugins before.

**Comment by craftcoin** [comment]
Fair enough: I couldn't ask for more. One additional question: Since I have made so many changes to the source today, I'm wondering if merging the sources together will actually simply merge code, or will it actually overwrite any changes I may have made today? 

I'm quite sure that is a stupid question, but perhaps one worth asking. I'm new to Github, so I'm still learning. 

Thanks for your help.

**Comment by CatmanIX** [comment]
Git's pretty good at intelligently merging changes without overwriting other changes, but just to make sure I've already merged your latest changes into this pull request so it shouldn't have any issues.

**Pull request merged**
